### ISSUE TITLE
implement the right hand side of exploreSystems (statistics)

### ISSUE THREAD

**Issue by jglyshaw** [oss-slu/dads#14]

**Comment by Lohit315** [comment]
I would like to address and try fixing this particular issue in the code. I have currently started working on this and once I get any progress, I will be attaching my forked repository for your reference so that you guys can review and see whether to merge it or not into the main branch.

**Comment by Lohit315** [comment]
[dads-main (2).zip](https://github.com/oss-slu/dads/files/14076875/dads-main.2.zip)
Please locate the file containing the addressed issues with the changes made. Feel free to use it if you find it useful
