### ISSUE TITLE
update in function details page - 1

### ISSUE THREAD

**Issue by suprajamannava17** [oss-slu/dads#169]
**Overview:**
Currently, the top-level information display for records is incomplete, with most, but not all, existing fields populated with data. Critical information such as label, domain, field of definition, standard model, and degree is either missing or not being displayed correctly. This issue aims to identify and rectify the data display issues to ensure that all relevant information is visible and accurately represented in the user interface.

**Acceptance Criteria:**
- [ ]  All relevant top-level fields (label, domain, field of definition, standard model, degree) display correctly in the UI, reflecting data from the database.

**Comment by dracpak** [comment]
Fixed with PR #170
