### ISSUE TITLE
improve docker instructions

### ISSUE THREAD

**Issue by AbhilashKotha** [oss-slu/dads#38]

**Comment by Rajdeep1311** [comment]
what exactly should be changed sir?

**Comment by AJelliss** [comment]
Hey, Im currently working on getting these instructions more OS friendly, and easier to read and understand for people who may not understand what it is they are doing with Docker, so that working with it down the line is easier

**Comment by Rajdeep1311** [comment]
Okay, sir, I can help if you need me.

**Comment by AJelliss** [comment]
I appreciate the offer, but I think I have this one covered!

**Comment by Rajdeep1311** [comment]
Okay sir
