### ISSUE TITLE
Clear filters functionality

### ISSUE THREAD

**Issue by AbhilashKotha** [oss-slu/dads#95]
**Is your feature request related to a problem? Please describe.**
Currently, when the users are browsing functions on Explore systems, they can only apply the filters and there is no option to remove all the filters with a single click.

**Describe the solution you'd like**
 The users should have the option to clear filters when they are on Explore systems. After clearing the filters, the user should be able to see all the functions again.

**Comment by LaxminarayanaV7416** [comment]
Hi @AbhilashKotha I would like to work on this issue, let me post my fixes once am ready with the fix
